name = "spark_multiway_trees"
description = "Multiway tree container written in SPARK"
version = "0.1.0-dev"

authors = ["Daniel King"]
maintainers = ["Daniel King <damaki.gh@gmail.com>"]
maintainers-logins = ["damaki"]
licenses = "Apache-2.0"
website = ""
tags = []

[build-switches]
"*".Ada_Version = "Ada2022"

[[depends-on]]
gnatprove = "^14.1.1"
